### ISSUE TITLE
Integration with the Site Inventory

### ISSUE THREAD

**Issue by zvfvrv** [5GEVE/mso-lo#18]
We need to integrate the mso-lo with the [Site Inventory]( https://github.com/5GEVE/site-inventory)

**Comment by TheWall89** [comment]
Let's keep SQLite for unit tests.

We need a mechanism to push VIMs retrieved in the NFVOs to the site inventory (periodically).
See threaded implementation:

- https://stackoverflow.com/questions/36342718/starting-background-daemon-in-flask-app
- https://stackoverflow.com/questions/47865418/thread-still-runs-when-flask-server-exits

**Comment by TheWall89** [comment]
Completed. I used apscheduler for background tasks. Only memory based backend.
