### ISSUE TITLE
VIM selection for OSM driver

### ISSUE THREAD

**Issue by TheWall89** [5GEVE/mso-lo#19]
Some orchestrators may need to select the VIM. We should push some configuration to the driver so it can manage this information.

~~Precondtiion: VIM information is in the SQLite~~
Vim information should be retrieved from NFVO (already implemented for OSM).

~~MSNO retrieves VIM information:~~

~~- Change paths to `/nfvo/{nfvo_id}/vim/{vim_id}~~

MSNO selects the VIM for instantiation:

- additional parameter in body of instantiate request

**Comment by TheWall89** [comment]
MSNO wants to deploy multi-vim stuff from our driver.
The need is to place some VNFs in specific VIMs.

Example with OSM cli:

`osm ns-create --ns_name ns_multisite_test --nsd_name multisite_2vnf_ns --vim_account 5GEVE-SITE2 --config '{vnf: [ {member-vnf-index: "1", vim_account: 5GEVE-SITE1}, {member-vnf-index: "2", vim_account: 5GEVE-SITE2} ], wim_account: False }'`

If it is possible from OSM REST API, we can implement this in our driver.

Anyway, since the MSO-LO implements a SOL005 interface, we need to wrap that `config` in the `POST /instantiate` request. Looking at SOL005 I can identify two candidate fields: "additionalParamsForVnf" and "additionalParamsForNs". The first has a defined structure by the standard but it does not mention the VIM. So I would prefer the second, that contains a list of key-value pairs with no restrictions.

**Comment by zvfvrv** [comment]
@TheWall89 i agree with you that the field _additionalParamsForNs_  is the best option

**Comment by TheWall89** [comment]
As showned in Marc's command, OSM uses the `member-vnf-index` to select the VIM account. The MSNO does not have this information. We delegate MSO-LO to retrieve this parameter.

The proposal:

1. MSNO sends an instantiation request with `additionalParamsForNs`. Inside there's a list with
```
[
{
  "vnfInstanceId": "3fa85f64-5717-4562-b3fc-2c963f66afa6", 
  "vimId": "07b2d32c-3cd0-421c-90f9-2e01b08ae602"
}
]
```
2. OSM driver maps `vnfInstanceId` to `member-vnf-index`
3. Instantiate request body for OSM contains the usual json, plus:
```
"vnf": [
  {
    "member-vnf-index": "1",
    "vim-id": "07b2d32c-3cd0-421c-90f9-2e01b08ae602"
  }
]
```

TODO:

- [ ] Update Openapi to include `additionalParamsForNs` in instantiate request
- [ ] Test OSM NBI for correct format of the message

**Comment by TheWall89** [comment]
Fix for `additionalParamsForNs`:

```
{
  "vnf": [
    { 
       "vnfInstanceId": "3fa85f64-5717-4562-b3fc-2c963f66afa6", 
       "vimId": "07b2d32c-3cd0-421c-90f9-2e01b08ae602"
    }
  ]
}

```

**Comment by TheWall89** [comment]
PR merged.
